import request from '@/utils/request'

export const getTemplatePage       = params     => request.get('/wr/template/page', { params })
export const getTemplateList       = ()         => request.get('/wr/template/list')
export const getTemplateDetail     = id         => request.get(`/wr/template/detail/${id}`)
export const getTemplateItems      = id         => request.get(`/wr/template/items/${id}`)
export const getTemplateFullDetail = id         => request.get(`/wr/template/detail/full/${id}`)
export const getTemplateRows       = id         => request.get(`/wr/template/rows/${id}`)
export const addTemplate           = data       => request.post('/wr/template/add', data)
export const updateTemplate        = data       => request.post('/wr/template/update', data)
export const deleteTemplate        = id         => request.post(`/wr/template/delete/${id}`)
export const updateTemplateStatus  = (id, status) => request.post(`/wr/template/status/${id}/${status}`)
export const saveTemplateItems     = (id, items)  => request.post(`/wr/template/items/save/${id}`, items)
export const saveTemplateRows      = (id, rows)   => request.post(`/wr/template/rows/save/${id}`, rows)
export const uploadFormatFile      = (itemId, formData) => request.post(`/wr/template/item/upload-format/${itemId}`, formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const deleteFormatFile      = itemId     => request.post(`/wr/template/item/delete-format/${itemId}`)
export const updateItemDict        = (itemId, dictCode) => request.post(`/wr/template/item/dict/${itemId}`, { dictCode: dictCode || null })
